[Service]
Host = "edgex-device-modbus"
Port = 49991
ConnectRetries = 3
Labels = []
OpenMsg = "device modbus started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res/docker"

[Logging]
EnableRemote = false
File = "./device-Modbus.log"
Level = "DEBUG"

# Pre-define Devices
[[DeviceList]]
  Name = "home temperature and humidity"
  Profile = "home-device-profile"
  Description = "this device test for modbus temperature and humidity"
  labels = [ "temp","humidity" ]
  [DeviceList.Addressable]
    name = "home-temp-humidity"
    Protocol = "TCP"
    Address = "192.168.0.110"
    Port = 5020
    Path = "1"

# [[DeviceList]]
#   Name = "Modbus RTU test device"
#   Profile = "Test.Device.Modbus.Profile"
#   Description = "This device is a product for monitoring and controlling digital inputs and outputs over a LAN."
#   labels = [ "Air conditioner","modbus RTU" ]
#   [DeviceList.Addressable]
#     name = "Gateway address 2"
#     Protocol = "RTU"
#     Address = "/tmp/slave,19200,8,1,0"
#     Path = "1"

# Pre-define Schedule Configuration
[[Schedules]]
Name = "10sec-schedule"
Frequency = "PT10S"

[[ScheduleEvents]]
Name = "Get humidity"
Schedule = "10sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/home temperature and humidity/humidity" 

[[ScheduleEvents]]
Name = "Set humidity"
Parameters = "[{\"humidity\": \"60.1\"}]"
Schedule = "10sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "Put"
  Path = "/api/v1/device/name/home temperature and humidity/humidity"

[[Schedules]]
Name = "5sec-schedule"
Frequency = "PT5S"

[[ScheduleEvents]]
Name = "Read temperature"
Schedule = "5sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/home temperature and humidity/temp"
